main:
  project_name:  ML deployment Heroku &FastAPI
  experiment_name: pipeline

data:
  cat_features : [
      "workclass",
      "education",
      "marital_status",
      "occupation",
      "relationship",
      "race",
      "sex",
      "native_country",
  ]
inference:
  columns:
    [ 'age',
      'workclass',
      'fnlgt',
      'education',
      'marital_status',
      'occupation',
      'relationship',
      'race',
      'sex',
      'hours-per-week',
      'native_country'
    ]
  update_keys:
      [
        ["marital_status","marital_status"],
        ["hours-per-week","hoursPerWeek"],
        ["native_country","nativeCountry"]
      ]