name: deploymentPipeline

on:
  push:
    branches: [ "main" ]

jobs:
  TriggerPipeline:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1
    - name: Pip install
      run: pip3 install -r requirements.txt
    - name: Setup DVC
      uses: iterative/setup-dvc@v1
    - name: Pull data from DVC
      run: dvc pull -R
    - name: Run Flake8
      run: |
        # check for syntax errors or undefined variables names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
    - name: Run pytest
      run: python -m pytest src/tests -rP
    - name: main
      env:
        ECR_URI: ${{ secrets.ECR_URI }}
      if: ${{ github.ref == 'refs/heads/main' }}
      run: |
        bash release.sh "main"