name: deploymentPipeline

on:
  push:
    branches: [ "main" ]

jobs:
  TriggerPipeline:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1
    - name: Copy files to the test website with the AWS CLI
      run: |
        aws s3 ls

    - name: main
      if: ${{ github.ref == 'refs/heads/main' }}
      run: bash release.sh "master" 